# Generated by Django 6.0.3 on 2026-04-02 03:38

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'topic',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(db_index=True, max_length=255)),
                ('primary_meaning', models.CharField(max_length=255)),
                ('pronunciation', models.CharField(blank=True, help_text='IPA', max_length=255)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('pronoun', 'Pronoun'), ('interjection', 'Interjection'), ('phrase', 'Phrase / Idiom'), ('other', 'Other')], default='other', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], default='A1', max_length=2)),
                ('audio_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vocabulary_word',
                'ordering': ['english_word'],
            },
        ),
        migrations.CreateModel(
            name='StudyDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_decks', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='vocabulary.topic')),
            ],
            options={
                'db_table': 'study_deck',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('flashcard', 'Flashcard'), ('typing', 'Typing'), ('mcq', 'Multiple Choice'), ('listening', 'Listening')], max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vocabulary.studydeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True)),
                ('daily_goal', models.PositiveSmallIntegerField(default=10, help_text='Target words per day', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('mastered', 'Mastered')], default='new', max_length=10)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=2.5, max_digits=4, validators=[django.core.validators.MinValueValidator(1.3), django.core.validators.MaxValueValidator(5.0)])),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('repetition', models.PositiveIntegerField(default=0)),
                ('correct_streak', models.PositiveIntegerField(default=0)),
                ('incorrect_streak', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progresses', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='vocabulary.vocabularyword')),
            ],
            options={
                'db_table': 'user_word_progress',
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyDeckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vocabulary.studydeck')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_items', to='vocabulary.vocabularyword')),
            ],
            options={
                'db_table': 'study_deck_item',
                'ordering': ['deck', 'display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='studydeck',
            name='words',
            field=models.ManyToManyField(related_name='decks', through='vocabulary.StudyDeckItem', to='vocabulary.vocabularyword'),
        ),
        migrations.CreateModel(
            name='StudyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('response_text', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300000)])),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_attempts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='vocabulary.studysession')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='vocabulary.vocabularyword')),
            ],
            options={
                'db_table': 'study_attempt',
                'ordering': ['-answered_at'],
            },
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('pronoun', 'Pronoun'), ('interjection', 'Interjection'), ('phrase', 'Phrase / Idiom'), ('other', 'Other')], default='other', max_length=20)),
                ('meaning_vi', models.CharField(max_length=255)),
                ('meaning_en', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='vocabulary.vocabularyword')),
            ],
            options={
                'db_table': 'word_meaning',
                'ordering': ['word', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='WordExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_en', models.TextField()),
                ('sentence_vi', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='vocabulary.vocabularyword')),
                ('meaning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examples', to='vocabulary.wordmeaning')),
            ],
            options={
                'db_table': 'word_example',
                'ordering': ['word', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WordTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_topics', to='vocabulary.topic')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_topics', to='vocabulary.vocabularyword')),
            ],
            options={
                'db_table': 'word_topic',
            },
        ),
        migrations.AddField(
            model_name='vocabularyword',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='words', through='vocabulary.WordTopic', to='vocabulary.topic'),
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('words_studied', models.PositiveSmallIntegerField(default=0)),
                ('words_mastered', models.PositiveSmallIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_activity',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='daily_activ_user_id_2596ee_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uq_user_daily_activity'), models.CheckConstraint(condition=models.Q(('words_studied__gte', models.F('words_mastered'))), name='chk_mastered_lte_studied')],
            },
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', '-started_at'], name='study_sessi_user_id_791aba_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'mode'], name='study_sessi_user_id_e2b967_idx'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='chk_session_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(('correct_answers__lte', models.F('total_questions'))), name='chk_correct_lte_total'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'status'], name='user_word_p_user_id_c6d8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'due_at'], name='user_word_p_user_id_87c48f_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['status', 'due_at'], name='user_word_p_status_177e7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='userwordprogress',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='uq_user_word_progress'),
        ),
        migrations.AddConstraint(
            model_name='userwordprogress',
            constraint=models.CheckConstraint(condition=models.Q(('ease_factor__gte', 1.3), ('ease_factor__lte', 5.0)), name='chk_ease_factor_range'),
        ),
        migrations.AddConstraint(
            model_name='userwordprogress',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gte', 0)), name='chk_interval_days_nonneg'),
        ),
        migrations.AddIndex(
            model_name='studydeckitem',
            index=models.Index(fields=['deck', 'display_order'], name='study_deck__deck_id_77fabf_idx'),
        ),
        migrations.AddConstraint(
            model_name='studydeckitem',
            constraint=models.UniqueConstraint(fields=('deck', 'word'), name='uq_word_per_deck'),
        ),
        migrations.AddConstraint(
            model_name='studydeck',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='uq_deck_title_per_owner'),
        ),
        migrations.AddIndex(
            model_name='studyattempt',
            index=models.Index(fields=['user', '-answered_at'], name='study_attem_user_id_be5863_idx'),
        ),
        migrations.AddIndex(
            model_name='studyattempt',
            index=models.Index(fields=['word', '-answered_at'], name='study_attem_word_id_a059df_idx'),
        ),
        migrations.AddIndex(
            model_name='studyattempt',
            index=models.Index(fields=['session', 'is_correct'], name='study_attem_session_3099a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyattempt',
            constraint=models.CheckConstraint(condition=models.Q(('response_time_ms__isnull', True), models.Q(('response_time_ms__gt', 0), ('response_time_ms__lte', 300000)), _connector='OR'), name='chk_response_time_range'),
        ),
        migrations.AddConstraint(
            model_name='wordmeaning',
            constraint=models.UniqueConstraint(fields=('word', 'part_of_speech', 'display_order'), name='uq_word_meaning_pos_order'),
        ),
        migrations.AddConstraint(
            model_name='wordexample',
            constraint=models.UniqueConstraint(fields=('word', 'sentence_en'), name='uq_word_example_sentence'),
        ),
        migrations.AddConstraint(
            model_name='wordtopic',
            constraint=models.UniqueConstraint(fields=('word', 'topic'), name='uq_word_topic'),
        ),
        migrations.AddIndex(
            model_name='vocabularyword',
            index=models.Index(fields=['difficulty_level'], name='vocabulary__difficu_83fc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyword',
            index=models.Index(fields=['is_active'], name='vocabulary__is_acti_901bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyword',
            index=models.Index(fields=['part_of_speech'], name='vocabulary__part_of_31e14a_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyword',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('english_word'), name='uq_vocabulary_word_lower'),
        ),
    ]
