# Generated by Django 6.0.3 on 2026-04-02 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=160)),
                ('lesson_order', models.PositiveIntegerField(default=1)),
                ('total_words', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_lesson',
                'ordering': ['track', 'lesson_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='studysession',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vocabulary.learninglesson'),
        ),
        migrations.CreateModel(
            name='LearningLessonWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_words', to='vocabulary.learninglesson')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_links', to='vocabulary.vocabularyword')),
            ],
            options={
                'db_table': 'learning_lesson_word',
                'ordering': ['lesson', 'display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='words',
            field=models.ManyToManyField(related_name='learning_lessons', through='vocabulary.LearningLessonWord', to='vocabulary.vocabularyword'),
        ),
        migrations.CreateModel(
            name='LearningTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_words', models.PositiveIntegerField(default=0)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_track',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['sort_order', 'is_active'], name='learning_tr_sort_or_a5e241_idx')],
            },
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='vocabulary.learningtrack'),
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_words', models.PositiveIntegerField(default=0)),
                ('mastered_words', models.PositiveIntegerField(default=0)),
                ('last_studied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='vocabulary.learninglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lesson_progress',
            },
        ),
        migrations.AddIndex(
            model_name='learninglessonword',
            index=models.Index(fields=['lesson', 'display_order'], name='learning_le_lesson__e4a4f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='learninglessonword',
            constraint=models.UniqueConstraint(fields=('lesson', 'word'), name='uq_lesson_word'),
        ),
        migrations.AddIndex(
            model_name='learninglesson',
            index=models.Index(fields=['track', 'is_active', 'lesson_order'], name='learning_le_track_i_247a85_idx'),
        ),
        migrations.AddConstraint(
            model_name='learninglesson',
            constraint=models.UniqueConstraint(fields=('track', 'slug'), name='uq_track_lesson_slug'),
        ),
        migrations.AddConstraint(
            model_name='learninglesson',
            constraint=models.UniqueConstraint(fields=('track', 'lesson_order'), name='uq_track_lesson_order'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'updated_at'], name='user_lesson_user_id_0ca03c_idx'),
        ),
        migrations.AddConstraint(
            model_name='userlessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uq_user_lesson_progress'),
        ),
        migrations.AddConstraint(
            model_name='userlessonprogress',
            constraint=models.CheckConstraint(condition=models.Q(('learned_words__gte', models.F('mastered_words'))), name='chk_lesson_mastered_lte_learned'),
        ),
    ]
