# Generated by Django 6.0.3 on 2026-04-02 04:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_learninglesson_studysession_lesson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglesson',
            name='estimated_minutes',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='skill_focus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='learninglesson',
            name='theory_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningtrack',
            name='target_level',
            field=models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], default='A2', max_length=2),
        ),
        migrations.AddField(
            model_name='learningtrack',
            name='track_group',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('skills', 'Skills'), ('exam', 'Exam')], default='vocabulary', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_level',
            field=models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], default='A1', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_goal',
            field=models.CharField(choices=[('communication', 'Giao tiep'), ('exam', 'Luyen thi'), ('work', 'Cong viec'), ('foundation', 'Mat goc')], default='foundation', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LessonQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pass_score', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('time_limit_seconds', models.PositiveIntegerField(default=600)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='vocabulary.learninglesson')),
            ],
            options={
                'db_table': 'lesson_quiz',
                'ordering': ['lesson', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='vocabulary.lessonquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blank', 'Fill in blank'), ('matching', 'Matching'), ('reading', 'Reading comprehension'), ('writing', 'Writing')], default='mcq', max_length=20)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('question_order', models.PositiveSmallIntegerField(default=1)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('accepted_answer', models.CharField(blank=True, max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vocabulary.lessonquiz')),
            ],
            options={
                'db_table': 'quiz_question',
                'ordering': ['quiz', 'question_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('choice_order', models.PositiveSmallIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='vocabulary.quizquestion')),
            ],
            options={
                'db_table': 'quiz_choice',
                'ordering': ['question', 'choice_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.PositiveSmallIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='vocabulary.quizattempt')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_answers', to='vocabulary.quizchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='vocabulary.quizquestion')),
            ],
            options={
                'db_table': 'quiz_answer',
            },
        ),
        migrations.CreateModel(
            name='UserLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], default='A1', max_length=2)),
                ('goal', models.CharField(choices=[('communication', 'Giao tiep'), ('exam', 'Luyen thi'), ('work', 'Cong viec'), ('foundation', 'Mat goc')], default='foundation', max_length=20)),
                ('duration_weeks', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_learning_path',
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='quiz_attemp_user_id_bee8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-started_at'], name='quiz_attemp_user_id_67c6ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'question_order'), name='uq_quiz_question_order'),
        ),
        migrations.AddConstraint(
            model_name='quizchoice',
            constraint=models.UniqueConstraint(fields=('question', 'choice_order'), name='uq_question_choice_order'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uq_attempt_question_answer'),
        ),
    ]
