# Generated by Django 6.0.3 on 2026-04-02 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_learninglesson_estimated_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_words', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='vocabulary.vocabularyword')),
            ],
            options={
                'db_table': 'user_favorite_word',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_favori_user_id_1401b3_idx'), models.Index(fields=['user', 'word'], name='user_favori_user_id_c747b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'word'), name='uq_user_favorite_word')],
            },
        ),
    ]
