# Generated by Django 6.0.3 on 2026-04-02 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_userfavoriteword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='vocabulary.learninglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_favorite_lesson',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_favori_user_id_3178b0_idx'), models.Index(fields=['user', 'lesson'], name='user_favori_user_id_c92811_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='uq_user_favorite_lesson')],
            },
        ),
    ]
